            
trigger: 
  - master

pool:
  name: Default

stages:
  - stage: CheckoutCode
    jobs:
      - job: 'Checkoutgitcode'
        steps:
          - checkout: self
  - stage: sonarscanning
    jobs: 
       - job: "sonarjob"
         steps:
           - task: SonarQubePrepare@7
             inputs:
               SonarQube: 'SonarqubeSCnew'
               scannerMode: 'other'
               projectKey: 'TestSonarDemo'
               projectName: 'BDDCucumberNew'



               